#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_NAME="dictionary-db"
WORKER_DIR="$ROOT/worker"
CHUNK_SIZE="${CHUNK_SIZE:-5000}"

# Verify deploy SQL exists (generated by generate-deploy-sql mode)
for f in "$ROOT/out/_words.sql" "$ROOT/out/_definitions.sql" "$ROOT/out/_deploy_meta.json"; do
  if [[ ! -f "$f" ]]; then
    echo "Error: $f not found. Run generate-deploy-sql first." >&2
    exit 1
  fi
done

cd "$WORKER_DIR"

echo "=== Deploying dictionary to D1: $DB_NAME ==="

# Ensure tables exist with correct schema (drop old schema if present)
npx wrangler d1 execute "$DB_NAME" --remote --command \
  "DROP TABLE IF EXISTS words; DROP TABLE IF EXISTS definitions; DROP TABLE IF EXISTS words_next; DROP TABLE IF EXISTS definitions_next;
   CREATE TABLE words (id INTEGER NOT NULL, word TEXT PRIMARY KEY);
   CREATE TABLE definitions (id INTEGER PRIMARY KEY, definition TEXT NOT NULL);"

DEFS_LINES=$(wc -l < "$ROOT/out/_definitions.sql")
WORDS_LINES=$(wc -l < "$ROOT/out/_words.sql")

# Apply definition changes first (words reference definition ids)
if [[ "$DEFS_LINES" -gt 0 ]]; then
  echo "Applying $DEFS_LINES definition operations..."
  split -l "$CHUNK_SIZE" "$ROOT/out/_definitions.sql" "$ROOT/out/_d_chunk_"
  TOTAL_D=$(ls "$ROOT"/out/_d_chunk_* | wc -l)
  I=0
  for chunk in "$ROOT"/out/_d_chunk_*; do
    I=$((I + 1))
    npx wrangler d1 execute "$DB_NAME" --remote --yes --file "$chunk"
    echo "  definitions: $I/$TOTAL_D"
  done
fi

# Apply word changes
if [[ "$WORDS_LINES" -gt 0 ]]; then
  echo "Applying $WORDS_LINES word operations..."
  split -l "$CHUNK_SIZE" "$ROOT/out/_words.sql" "$ROOT/out/_w_chunk_"
  TOTAL_W=$(ls "$ROOT"/out/_w_chunk_* | wc -l)
  I=0
  for chunk in "$ROOT"/out/_w_chunk_*; do
    I=$((I + 1))
    npx wrangler d1 execute "$DB_NAME" --remote --yes --file "$chunk"
    echo "  words: $I/$TOTAL_W"
  done
fi

# Cleanup temp files
rm -f "$ROOT"/out/_words.sql "$ROOT"/out/_definitions.sql \
      "$ROOT"/out/_w_chunk_* "$ROOT"/out/_d_chunk_*

echo "=== D1 deployment complete ==="
